Data Preprocessing

Importing the Required Libraries

In [7]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

Import the Dataset

In [9]:
dataset = pd.read_csv("D:/AIML/Machine Learning/Part 1 - Data Preprocessing/Section 2 Part 1 - Data Preprocessing/Python/Data.csv")
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

print the values of 'X'

print(x)

Print the Values of 'Y'

In [13]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


Data Preprocessing

Taking Care of Missing Data

In [16]:
# Import the Required packages for Data Preprocessing

# SimpleImputer from SkLearn is required for Data Preprocessing

# SimpleImputer is a Class in sklearn.impute module 

from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')

# x[:] // refers to include all the rows in Transformation
# x[1:3] // refers to include only the 2nd & 3rd columns only because the 1st column contains "Categorical Value" 
# and we excluded the 4th column because it is a target variable (Which is also a "Categorical Value")

imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])

Print the Values in "x" to see if null values have been filled with mean values

In [18]:
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


Encoding categorical Values into Numerical Values

Encoding the Independent Variable (Feature's)

In [21]:
# Import the Classes required for Encoding Categorical Value's

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder 

columnTransform = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(columnTransform.fit_transform(x))

In [22]:
print(x)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


Encoding the Dependent Variable (Target Variable) 'y'

In [33]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [35]:
print(y)

[0 1 0 0 1 1 0 1 0 1]


Splitting the Dataset into Training set and Test Set

In [42]:
# sklearn.model_selection module has a class named train_test_split which is 
# used to split the dataset.

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.33, 
                                                    random_state=42)

In [44]:
print(X_train)

[[1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]]


In [46]:
print(X_test)

[[0.0 1.0 0.0 50.0 83000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 35.0 58000.0]
 [1.0 0.0 0.0 44.0 72000.0]]


In [48]:
print(y_train)

[1 0 1 1 0 0]


In [50]:
print(y_test)

[0 1 1 0]


Feature Scaling

Feature Sccaling can be done through a class called StandardScalar of the 
sklearn.preprocessing module

In [54]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:, 3:] = sc.fit_transform(X_train[:, 3:])
X_test[:, 3:] = sc.transform(X_test[:, 3:])

In [56]:
print(X_train)

[[1.0 0.0 0.0 1.7749251497827823 1.8147396179442679]
 [0.0 1.0 0.0 -1.634614861262403 -0.9851443640268875]
 [1.0 0.0 0.0 -0.30868263474483093 0.4707953065981133]
 [0.0 1.0 0.0 0.25957403376269994 0.10992137114405362]
 [0.0 0.0 1.0 -0.11926374524232065 -0.20117684907496403]
 [0.0 0.0 1.0 0.028062057704076396 -1.20913508258458]]


In [62]:
print(X_test)

[[0.0 1.0 0.0 2.153762928787803 2.262721055059653]
 [0.0 0.0 1.0 -2.2028715297699337 -1.6571165196999649]
 [1.0 0.0 0.0 -0.6875204137498515 -0.5371629269115027]
 [1.0 0.0 0.0 1.017249591772741 1.0307721029923445]]
