Data Preprocessing

Importing the Required Libraries

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

Import the Dataset

dataset = pd.read_csv("D:/AIML/Machine Learning/Part 1 - Data Preprocessing/Section 2 Part 1 - Data Preprocessing/Python/Data.csv")
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

print the values of 'X'

print(x)

Print the Values of 'Y'

In [15]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


Data Preprocessing

Taking Care of Missing Data

In [30]:
# Import the Required packages for Data Preprocessing

# SimpleImputer from SkLearn is required for Data Preprocessing

# SimpleImputer is a Class in sklearn.impute module 

from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')

# x[:] // refers to include all the rows in Transformation
# x[1:3] // refers to include only the 2nd & 3rd columns only because the 1st column contains "Categorical Value" 
# and we excluded the 4th column because it is a target variable (Which is also a "Categorical Value")

imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])

Print the Values in "x" to see if null values have been filled with mean values

In [35]:
print(x)

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

Encoding categorical Values into Numerical Values

Encoding the Independent Variable (Feature's)

In [42]:
# Import the Classes required for Encoding Categorical Value's

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder 

columnTransform = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(columnTransform.fit_transform(x))

In [44]:
print(x)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]
