Multiple Linear Regression

Import the Required Libraries

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

Load the Dataset

In [6]:
df = pd.read_csv("D:/AIML/Machine Learning/Part 2 - Regression/Section 5 - Multiple Linear Regression/Python/50_Startups.csv")
X = df.iloc[:, :-1].values
y = df.iloc[:, -1].values

In [17]:
df.head()
# print(X)

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [16]:
print(y)

Encoding the Categorical values

In [19]:
# State column has Categorical values it needs to be encoded into Numerical 
# values through OneHotEncoding

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [3])], remainder = 'passthrough')
X = np.array(ct.fit_transform(X))

In [21]:
print(X)

[[0.0 0.0 1.0 165349.2 136897.8 471784.1]
 [1.0 0.0 0.0 162597.7 151377.59 443898.53]
 [0.0 1.0 0.0 153441.51 101145.55 407934.54]
 [0.0 0.0 1.0 144372.41 118671.85 383199.62]
 [0.0 1.0 0.0 142107.34 91391.77 366168.42]
 [0.0 0.0 1.0 131876.9 99814.71 362861.36]
 [1.0 0.0 0.0 134615.46 147198.87 127716.82]
 [0.0 1.0 0.0 130298.13 145530.06 323876.68]
 [0.0 0.0 1.0 120542.52 148718.95 311613.29]
 [1.0 0.0 0.0 123334.88 108679.17 304981.62]
 [0.0 1.0 0.0 101913.08 110594.11 229160.95]
 [1.0 0.0 0.0 100671.96 91790.61 249744.55]
 [0.0 1.0 0.0 93863.75 127320.38 249839.44]
 [1.0 0.0 0.0 91992.39 135495.07 252664.93]
 [0.0 1.0 0.0 119943.24 156547.42 256512.92]
 [0.0 0.0 1.0 114523.61 122616.84 261776.23]
 [1.0 0.0 0.0 78013.11 121597.55 264346.06]
 [0.0 0.0 1.0 94657.16 145077.58 282574.31]
 [0.0 1.0 0.0 91749.16 114175.79 294919.57]
 [0.0 0.0 1.0 86419.7 153514.11 0.0]
 [1.0 0.0 0.0 76253.86 113867.3 298664.47]
 [0.0 0.0 1.0 78389.47 153773.43 299737.29]
 [0.0 1.0 0.0 73994.56 122782.75 3

Spit the Dataset into Training and Test Dataset

In [24]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

Training the Multiple Linear Regression Model on the Training DataSet

In [27]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression()

Predicting the Test Set Results

In [36]:
y_pred = regressor.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred), 1), y_test.reshape(len(y_test),1)),1))

[[126187.36 134307.35]
 [ 85719.46  81005.76]
 [ 99648.03  99937.59]
 [ 45664.96  64926.08]
 [127106.84 125370.37]
 [ 51752.87  35673.41]
 [109033.36 105733.54]
 [100575.61 107404.34]
 [ 97877.86  97427.84]
 [111674.71 122776.86]
 [128750.99 141585.52]
 [174097.6  166187.94]
 [ 93630.    89949.14]
 [148426.42 152211.77]
 [172333.63 182901.99]
 [155858.61 156122.51]
 [ 77089.61  77798.83]]


To predict the profit of any start-up

In [39]:
features = [165349.20, 136897.80, 471784.10, 1, 0, 0]

In [41]:
regressor_coef = [0.8, 0.02, 0.05, 500, 300, 100]
regressor_intercept = 20000

In [45]:
profit = np.dot(features, regressor_coef) + regressor_intercept
print(f"predicted profit : {profit}")

predicted profit : 179106.521
